### ISSUE TITLE
Potential step missing

### ISSUE THREAD

**Issue by berserkingyadis** [hlarsen/cmangos-vagrant#1]
I looked at the installation instructions from cmangos and on there is a step that you skipped.

This is the step: https://github.com/cmangos/issues/wiki/Installation-Instructions#initialize-mangos-database

Is initializing the mangos database not needed? You are issuing these commands:

``` bash
mysql -uroot -p"$MYSQL_SERVER_ROOT_PASS" < create/db_create_mysql.sql
echo "FLUSH PRIVILEGES;" | mysql -uroot -p"$MYSQL_SERVER_ROOT_PASS"
mysql -uroot -p"$MYSQL_SERVER_ROOT_PASS" characters < base/characters.sql
mysql -uroot -p"$MYSQL_SERVER_ROOT_PASS" realmd < base/realmd.sql
```

I thought that one must do
```
mysql -uroot -p"$MYSQL_SERVER_ROOT_PASS" mangos < base/mangos.sql
```
after the `db_create_mysql.sql`

**Comment by hlarsen** [comment]
might have just forgot; i added it in along with some other changes and will test/push soon.

thanks for spotting it!

**Comment by hlarsen** [comment]
ok, added that back in - classic compiles, but i didn't have a client setup to connect with... please let me know if there are still issues.
